using Ex1;
Console.WriteLine("Insira a marca do carro: ");
string marca = Console.ReadLine();
Console.WriteLine("Insira o modelo do carro: ");
string modelo = Console.ReadLine();
Console.WriteLine("Insira a placa do carro: ");
string placa = Console.ReadLine();
Console.WriteLine("Insira a cor do carro: ");
string cor = Console.ReadLine();
Console.WriteLine("Insira a quilometragem do carro: ");
float km = float.Parse(Console.ReadLine());
Console.WriteLine("O carro esta ligado? ");
bool isLigado = bool.Parse(Console.ReadLine());
Console.WriteLine("Insira a quantidade de combustivel: ");
int litrosCombustivel = int.Parse(Console.ReadLine());
Console.WriteLine("Insira a velocidade do carro: ");
int velocidade = int.Parse(Console.ReadLine());
Console.WriteLine("Insira o valor do carro: ");
double preco = double.Parse(Console.ReadLine());

Veiculo veiculo = new Veiculo(marca, modelo, placa, cor, km, isLigado, litrosCombustivel, velocidade, preco);

Console.WriteLine(veiculo.ToString());
Console.WriteLine("Escolha a nova cor: ");
string novaCor = Console.ReadLine();
veiculo.Pintar(novaCor);
Console.WriteLine($"Nova cor: {veiculo.Cor}");
Console.WriteLine(veiculo);
Console.WriteLine($"Velocidade: {veiculo.Velocidade}");
Console.WriteLine("Freando");
veiculo.Frear();
Console.WriteLine($"Velocidade: {veiculo.Velocidade}");
Console.WriteLine("Acelerando");
veiculo.Acelerar();
Console.WriteLine($"Velocidade: {veiculo.Velocidade}");
Console.WriteLine("Informe o valor a abastecer: ");
int combustivel = int.Parse(Console.ReadLine());    
veiculo.Abastecer(combustivel);
Console.WriteLine($"Combustivel no tanque: {veiculo.LitrosCombustivel}");
Console.WriteLine($"O carro esta ligado? {veiculo.IsLigado}");
veiculo.Ligar();
Console.WriteLine($"O carro esta ligado? {veiculo.IsLigado}");
veiculo.Desligar();